import { defineConfig } from "tsdown";

export default defineConfig({
  entry: ["./src/index.tsx"],
  platform: "neutral",
  external: [
    "react",
    "react-dom",
    "@base-ui/react",
    "@hugeicons-pro/core-stroke-rounded",
    "@hugeicons/react",
    "tailwind-variants",
    "cmdk",
    "country-flag-icons",
    "culori",
    "embla-carousel",
    "embla-carousel-react",
    "frimousse",
    "input-otp",
    "media-chrome",
    "qrcode",
    "react-day-picker",
    "react-dropzone",
    "react-fast-marquee",
    "react-resizable-panels",
    "react-textarea-autosize",
    "recharts",
    "vaul",
  ],
  dts: true,
  format: ["esm"],
  clean: true,
});
